### ISSUE TITLE
java.lang.IllegalArgumentException: input == null!

### ISSUE THREAD

**Issue by j-selby** [j-selby/EscapistsEditor#12]
View details in Rollbar: [https://rollbar.com/jselby/Unofficial-Escapists-Editor/items/12/](https://rollbar.com/jselby/Unofficial-Escapists-Editor/items/12/)

```

java.lang.IllegalArgumentException: input == null!
  javax.imageio.ImageIO.read (ImageIO.java:1388)
  net.jselby.escapists.editor.elements.RenderView.updateTiling (RenderView.java:590)
  net.jselby.escapists.editor.elements.RenderView.<init> (RenderView.java:78)
  net.jselby.escapists.EscapistsEditor.main (EscapistsEditor.java:390)
```

**Comment by 1Gamers** [comment]
Line 590 is killing the startup

``` java
icons.add(new ImageIcon(ImageIO.read(getClass().getResource("/defaulttile.png"))));
```

The image defaulttile.png can't be found:

![screen shot 2015-04-07 at 7 17 03 pm](https://cloud.githubusercontent.com/assets/6701991/7030198/cc04f6ce-dd5a-11e4-9c5e-5b0b2a11b2c6.png)
![screen shot 2015-04-07 at 7 17 22 pm](https://cloud.githubusercontent.com/assets/6701991/7030199/cfedb226-dd5a-11e4-84e6-03a45199fb98.png)

![screen shot 2015-04-07 at 7 19 40 pm](https://cloud.githubusercontent.com/assets/6701991/7030241/1631cbfa-dd5b-11e4-8ff6-792290709659.png)

Nowhere to be seen

Note: I am running the escapists on Mac OS X (XQuartz and Wineskin)

**Comment by 1Gamers** [comment]
j-selby I found the solution to that problem 

Image: 
![defaulttile](https://cloud.githubusercontent.com/assets/6701991/7032129/75e5cddc-dd68-11e4-907c-ec955a335f44.png)

problem--

``` java
icons.add(new ImageIcon(ImageIO.read(getClass().getResource("/defaulttile.png"))));
```

fix--

``` java
final ImageIcon icn = new ImageIcon(ImageIO.read(getClass().getResource("/defaulttile.png")));
icons.add(icn);
```

**Comment by j-selby** [comment]
Have you added src/main/resources as a resource folder? This compiles fine using Maven or intellij
