### ISSUE TITLE
java.lang.IllegalArgumentException: input == null!

### ISSUE THREAD

**Issue by j-selby** [j-selby/EscapistsEditor#13]
View details in Rollbar: [https://rollbar.com/jselby/Unofficial-Escapists-Editor/items/13/](https://rollbar.com/jselby/Unofficial-Escapists-Editor/items/13/)

```

java.lang.IllegalArgumentException: input == null!
  javax.imageio.ImageIO.read (ImageIO.java:1388)
  net.jselby.escapists.editor.elements.RenderView.<init> (RenderView.java:559)
  net.jselby.escapists.EscapistsEditor.main (EscapistsEditor.java:390)
```

**Comment by 1Gamers** [comment]
Image--

![icon](https://cloud.githubusercontent.com/assets/6701991/7032250/58c96834-dd69-11e4-911f-089a080c9c4a.png)

Add image to src/main/java

Example in eclipse

![screen shot 2015-04-07 at 9 03 33 pm](https://cloud.githubusercontent.com/assets/6701991/7032289/9e304a32-dd69-11e4-9193-19c84142ddbd.png)

Adding the icon image for app will fix and let it launch

Application Icon doesn't show in Mac OS X I'll fix that in a second

**Comment by j-selby** [comment]
See other input==null issue
